server:
  port: 8080

spring:
  application:
    name: billing-api
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: INFO
    fr.caassurances.kata.billing.infrastructure: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] [%t] %c{1} : %m%n"

management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

resilience4j.circuitbreaker:
  instances:
    catalogService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000ms

app:
  external-api:
    catalog-url: "http://localhost:8080/external-api"